import React from 'react'
import { Contract, Account, Provider } from 'starknet'
// Create a file called abi.json in  your assets folder under src and paste the sierra.json file generated by scarb build that you declared earlier.
import { abi } from './assets/abi.json'
const PRIVATE_KEY =  "0xb09c8f6b0c2e03091eb8bb8e4f44072"

const ACCOUNT_ADDRESS = "0x5edceb87f7fd9cc2d0f8f8a9537776d3b28cb951916a6e753c24a64bf169fe4"

const CONTRACT_ADDRESS =  "0x2cd40c34649ecacaf0dbeb9cc37054ffc1042032182e9cdc436acbbe5d5b1dd"

const provider = new Provider({ rpc: { nodeUrl: "http://0.0.0.0:5050/rpc" } })
const account = new Account(provider, ACCOUNT_ADDRESS, PRIVATE_KEY)
const contract = new Contract(abi, CONTRACT_ADDRESS, account)

const App = () => {
  console.log(PRIVATE_KEY)
  async function callContract(){
      const res = await contract.get_vote_status()
      console.log(res.toString())
  }

  return (
    <div>
    <button onClick={callContract}>Call Contract</button>
    </div>
)
}

export default App